name: simple_food_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

isar_version: &isar_version 3.1.0 # define the version to be used

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^8.0.0
  introduction_screen: ^3.1.14
  shared_preferences: ^2.3.2
  flutter_bloc: 8.1.5
  wheel_slider: ^1.2.1
  bottom_picker: ^2.8.0
  isar: *isar_version
  isar_flutter_libs: *isar_version
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 1.25.7
  flutter_lints: ^4.0.0
  mocktail: 1.0.3
  bloc_test: 9.1.7
  isar_generator: *isar_version
  build_runner: 2.4.10

flutter:
  uses-material-design: true
